version: "3.8"

services:
  # Next.js Application
  app:
    # GANTI 'username' dan 'reponame' dengan milikmu, semuanya huruf kecil!
    image: ghcr.io/ucyenyen/rectorcupuc-2026:latest
    container_name: rectorcup-app
    restart: unless-stopped
    expose:
      - "3000"
    env_file: .env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - global_proxy
    volumes:
      - ./.env:/app/.env:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./uploads:/app/public/uploads

  # Prisma Studio
  studio:
    # Gunakan image yang sama dengan app
    image: ghcr.io/ucyenyen/rectorcupuc-2026:latest
    container_name: rectorcup-studio
    command: pnpm prisma studio --port 5557 --browser none
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    expose:
      - "5557"
    networks:
      - global_proxy
      - rectorcup_internal
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    profiles:
      - manual

networks:
  global_proxy:
    external: true
  rectorcup_internal:
    driver: bridge